---
name: WWW-Pastebin-PastebinCom-Create
version: 0.002
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: paste to L<http://pastebin.com> from Perl.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  LWP::UserAgent: 2.036
  URI: 1.35
  overload: 1.04
build_requires:
  Test::More: 0
provides:
  WWW::Pastebin::PastebinCom::Create:
    file: lib/WWW/Pastebin/PastebinCom/Create.pm
    version: 0.002
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
